name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ here to escape them too
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'feature'
    branch:
      - '/^feat\/.+/'
    title:
      - '/^feat(\(.+?\))?:/i'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
    title:
      - '/^fix(\(.+?\))?:/i'
  - label: 'chore'
    branch:
      - '/^chore\/.+/'
    title:
      - '/^chore(\(.+?\))?:/i'